version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - TZ=Europe/Prague
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  data-fetcher:
    build:
      context: ./data-fetcher
      dockerfile: dockerize/Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-postgres}
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq
    depends_on:
      - db
      - rabbitmq

  scheduler:
    build: ./scheduler
    environment:
      - TZ=Europe/Prague
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq
    depends_on:
      - data-fetcher
      - rabbitmq

  analysis-api:
    build: ./analysis-api
    environment:
      - SECRET_KEY=${SECRET_KEY:-dev}
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-postgres}
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq
    ports:
      - "5000:5000"
    depends_on:
      - db
      - data-fetcher
      - rabbitmq

  web-frontend:
    build: ./web-frontend
    ports:
      - "3000:3000"
    depends_on:
      - analysis-api

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - TZ=Europe/Prague
    ports:
      - "5672:5672"
      - "15672:15672"

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq
      - FLOWER_PORT=8888
      - TZ=Europe/Prague
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq

volumes:
  db_data: {}
