version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  data-fetcher:
    build:
      context: ./data-fetcher
      dockerfile: dockerize/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
      - rabbitmq
    
  analysis-api:
    build: ./analysis-api
    depends_on:
      - db
      - data-fetcher

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - FLOWER_PORT=8888
    ports:
      - "8889:8888"
    depends_on:
      - rabbitmq

volumes:
  db_data: {}
