version: "3.8"

services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - TZ=Europe/Prague
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  data-fetcher:
    build:
      context: ./data-fetcher
      dockerfile: dockerize/Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-postgres}
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq
      - TZ=Europe/Prague
    depends_on:
      - db
      - rabbitmq

  analysis-api:
    build: ./analysis-api
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-postgres}
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq
      - TZ=Europe/Prague
    ports:
      - "5000:5000"
    depends_on:
      - db
      - data-fetcher
      - rabbitmq

  web-frontend:
    build:
      context: ./web-frontend
      dockerfile: dockerize/Dockerfile
      args:
        - API_URL=${ANALYSIS_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - analysis-api

  rabbitmq:
    image: rabbitmq:3.11
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - TZ=Europe/Prague
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: {}
