"""Add account updates table

Revision ID: 7c39543d5e19
Revises: bd7e30f8050f
Create Date: 2023-01-16 10:18:28.489072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '7c39543d5e19'
down_revision = 'bd7e30f8050f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='updatestatus'), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_bank', ENUM('CSAC', 'FIO', 'KB', name='bank', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['account_number', 'account_bank'], ['account.number', 'account.bank'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_update')
    # ### end Alembic commands ###
