"""Add search columns

Revision ID: 94cd00dd94eb
Revises: b865fa38c42c
Create Date: 2023-03-02 10:22:26.519835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cd00dd94eb'
down_revision = 'b865fa38c42c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name_search', sa.String(), nullable=True))
    op.add_column('account', sa.Column('owner_search', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'owner_search')
    op.drop_column('account', 'name_search')
    # ### end Alembic commands ###
