"""Initial migration

Revision ID: b865fa38c42c
Revises: 
Create Date: 2023-01-30 10:09:54.641418

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b865fa38c42c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('number', sa.String(length=17), sa.CheckConstraint('LENGTH(number) = 17'), nullable=False),
    sa.Column('bank', sa.Enum('CSAS', 'CSOB', 'FIO', 'KB', 'MONETA', 'RB', name='bank'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('CZK', 'EUR', 'USD', 'GBP', name='currency'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('last_fetched', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('number', 'bank')
    )
    op.create_table('account_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='updatestatus'), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_bank', sa.Enum('CSAS', 'CSOB', 'FIO', 'KB', 'MONETA', 'RB', name='bank'), nullable=False),
    sa.ForeignKeyConstraint(['account_number', 'account_bank'], ['account.number', 'account.bank'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('CZK', 'EUR', 'USD', 'GBP', name='currency'), nullable=False),
    sa.Column('counter_account', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('INCOMING', 'OUTGOING', name='transactiontype'), nullable=False),
    sa.Column('str_type', sa.String(), nullable=False),
    sa.Column('variable_symbol', sa.String(), nullable=False),
    sa.Column('constant_symbol', sa.String(), nullable=False),
    sa.Column('specific_symbol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ca_identifier', sa.String(length=8), nullable=True),
    sa.Column('ca_name', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('MESSAGE', 'ATM', 'FEE', 'TAX', 'CARD', name='transactioncategory'), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_bank', sa.Enum('CSAS', 'CSOB', 'FIO', 'KB', 'MONETA', 'RB', name='bank'), nullable=False),
    sa.ForeignKeyConstraint(['account_number', 'account_bank'], ['account.number', 'account.bank'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('account_update')
    op.drop_table('account')
    # ### end Alembic commands ###
