"""Initial migration

Revision ID: bd7e30f8050f
Revises: 
Create Date: 2023-01-15 20:33:50.038624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7e30f8050f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('number', sa.String(length=17), sa.CheckConstraint('LENGTH(number) = 17'), nullable=False),
    sa.Column('bank', sa.Enum('CSAC', 'FIO', 'KB', name='bank'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('CZK', 'EUR', 'USD', 'GBP', name='currency'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('last_fetched', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('number', 'bank')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('counter_account', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('INCOMING', 'OUTGOING', name='transactiontype'), nullable=False),
    sa.Column('str_type', sa.String(), nullable=False),
    sa.Column('variable_symbol', sa.String(), nullable=False),
    sa.Column('constant_symbol', sa.String(), nullable=False),
    sa.Column('specific_symbol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_bank', sa.Enum('CSAC', 'FIO', 'KB', name='bank'), nullable=False),
    sa.ForeignKeyConstraint(['account_number', 'account_bank'], ['account.number', 'account.bank'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('account')
    # ### end Alembic commands ###
