"""Initial migration

Revision ID: e67732f5a2c9
Revises: 
Create Date: 2023-03-02 11:40:15.090374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67732f5a2c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('number', sa.String(length=17), nullable=False),
    sa.Column('bank', sa.Enum('CSAS', 'CSOB', 'FIO', 'KB', 'MONETA', 'RB', name='bank'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_search', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_search', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('number', 'bank')
    )
    op.create_table('account_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILURE', name='updatestatus'), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_bank', sa.Enum('CSAS', 'CSOB', 'FIO', 'KB', 'MONETA', 'RB', name='bank'), nullable=False),
    sa.ForeignKeyConstraint(['account_number', 'account_bank'], ['account.number', 'account.bank'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('counter_account', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('INCOMING', 'OUTGOING', name='transactiontype'), nullable=False),
    sa.Column('str_type', sa.String(), nullable=False),
    sa.Column('variable_symbol', sa.String(), nullable=False),
    sa.Column('constant_symbol', sa.String(), nullable=False),
    sa.Column('specific_symbol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ca_identifier', sa.String(length=8), nullable=True),
    sa.Column('ca_name', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('MESSAGE', 'ATM', 'FEE', 'TAX', 'CARD', name='transactioncategory'), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_bank', sa.Enum('CSAS', 'CSOB', 'FIO', 'KB', 'MONETA', 'RB', name='bank'), nullable=False),
    sa.ForeignKeyConstraint(['account_number', 'account_bank'], ['account.number', 'account.bank'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_ca_identifier'), 'transaction', ['ca_identifier'], unique=False)
    op.create_index(op.f('ix_transaction_counter_account'), 'transaction', ['counter_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_counter_account'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_ca_identifier'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('account_update')
    op.drop_table('account')
    # ### end Alembic commands ###
