"""Initial migration

Revision ID: e830b9a40f9f
Revises: 
Create Date: 2022-12-23 11:16:20.923912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e830b9a40f9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('number', sa.String(length=17), nullable=False),
    sa.Column('bank_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('CZK', 'EUR', 'USD', 'GBP', name='currency'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('last_fetched', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('counter_account', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('variable_symbol', sa.String(), nullable=False),
    sa.Column('constant_symbol', sa.String(), nullable=False),
    sa.Column('specific_symbol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(length=17), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('account')
    # ### end Alembic commands ###
