"""add transaction fields

Revision ID: fe6aa43174bf
Revises: 7c39543d5e19
Create Date: 2023-01-29 10:11:27.248925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'fe6aa43174bf'
down_revision = '7c39543d5e19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    transactioncategory = postgresql.ENUM('MESSAGE', name='transactioncategory')
    transactioncategory.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('category', sa.Enum('MESSAGE', name='transactioncategory'), nullable=True))
    op.add_column('transaction', sa.Column('currency', postgresql.ENUM('CZK', 'EUR', 'USD', 'GBP', name='currency', create_type=False), nullable=False))
    op.add_column('transaction', sa.Column('identifier', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'category')
    op.drop_column('transaction', 'identifier')
    op.drop_column('transaction', 'currency')

    transactioncategory = postgresql.ENUM('MESSAGE', name='transactioncategory')
    transactioncategory.drop(op.get_bind())
    # ### end Alembic commands ###
